In [3]:
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import ta
import numpy as np
pd.options.mode.chained_assignment = None

In [4]:
tickers = pd.read_html("https://en.wikipedia.org/wiki/NIFTY_50", match="Company Name")[0]

In [5]:
tickers['Symbol'] = tickers['Symbol'].astype(str) + '.NS'
tickers

Company Name         Symbol                      Sector
0                       Adani Ports  ADANIPORTS.NS              Infrastructure
1                  Apollo Hospitals  APOLLOHOSP.NS                  Healthcare
2                      Asian Paints  ASIANPAINT.NS              Consumer Goods
3                         Axis Bank    AXISBANK.NS                     Banking
4                        Bajaj Auto  BAJAJ-AUTO.NS                  Automobile
5                     Bajaj Finance  BAJFINANCE.NS          Financial Services
6                     Bajaj Finserv  BAJAJFINSV.NS          Financial Services
7                     Bharti Airtel  BHARTIARTL.NS           Telecommunication
8                  Bharat Petroleum        BPCL.NS          Energy - Oil & Gas
9              Britannia Industries   BRITANNIA.NS              Consumer Goods
10                            Cipla       CIPLA.NS             Pharmaceuticals
11                       Coal India   COALINDIA.NS                      Metals
12              Divi's Laboratories    DIVISLAB.NS             Pharmaceuticals
13         Dr. Reddy's Laboratories     DRREDDY.NS             Pharmaceuticals
14                    Eicher Motors   EICHERMOT.NS                  Automobile
15                Grasim Industries      GRASIM.NS                      Cement
16                 HCL Technologies     HCLTECH.NS      Information Technology
17                             HDFC        HDFC.NS          Financial Services
18                        HDFC Bank    HDFCBANK.NS                     Banking
19                        HDFC Life    HDFCLIFE.NS          Financial Services
20                    Hero MotoCorp  HEROMOTOCO.NS                  Automobile
21              Hindalco Industries    HINDALCO.NS                      Metals
22               Hindustan Unilever  HINDUNILVR.NS              Consumer Goods
23                       ICICI Bank   ICICIBANK.NS                     Banking
24                    IndusInd Bank  INDUSINDBK.NS                     Banking
25                          Infosys        INFY.NS      Information Technology
26                      ITC Limited         ITC.NS              Consumer Goods
27                        JSW Steel    JSWSTEEL.NS                      Metals
28              Kotak Mahindra Bank   KOTAKBANK.NS                     Banking
29                  Larsen & Toubro          LT.NS                Construction
30              Mahindra & Mahindra         M&M.NS                  Automobile
31                    Maruti Suzuki      MARUTI.NS                  Automobile
32                     Nestlé India   NESTLEIND.NS              Consumer Goods
33                             NTPC        NTPC.NS              Energy - Power
34  Oil and Natural Gas Corporation        ONGC.NS          Energy - Oil & Gas
35  Power Grid Corporation of India   POWERGRID.NS              Energy - Power
36              Reliance Industries    RELIANCE.NS          Energy - Oil & Gas
37              State Bank of India        SBIN.NS                     Banking
38       SBI Life Insurance Company     SBILIFE.NS          Financial Services
39                    Shree Cements    SHREECEM.NS                      Cement
40               Sun Pharmaceutical   SUNPHARMA.NS             Pharmaceuticals
41                      Tata Motors  TATAMOTORS.NS                  Automobile
42                       Tata Steel   TATASTEEL.NS                      Metals
43        Tata Consultancy Services         TCS.NS      Information Technology
44           Tata Consumer Products  TATACONSUM.NS              Consumer Goods
45                    Tech Mahindra       TECHM.NS      Information Technology
46                    Titan Company       TITAN.NS           Consumer Durables
47                 UltraTech Cement  ULTRACEMCO.NS                      Cement
48        United Phosphorus Limited         UPL.NS                   Chemicals
49                            Wipro       WIPRO.NS  Information Technolog

In [6]:
symbols = tickers.Symbol.to_list()

In [7]:
symbols

['ADANIPORTS.NS',
 'APOLLOHOSP.NS',
 'ASIANPAINT.NS',
 'AXISBANK.NS',
 'BAJAJ-AUTO.NS',
 'BAJFINANCE.NS',
 'BAJAJFINSV.NS',
 'BHARTIARTL.NS',
 'BPCL.NS',
 'BRITANNIA.NS',
 'CIPLA.NS',
 'COALINDIA.NS',
 'DIVISLAB.NS',
 'DRREDDY.NS',
 'EICHERMOT.NS',
 'GRASIM.NS',
 'HCLTECH.NS',
 'HDFC.NS',
 'HDFCBANK.NS',
 'HDFCLIFE.NS',
 'HEROMOTOCO.NS',
 'HINDALCO.NS',
 'HINDUNILVR.NS',
 'ICICIBANK.NS',
 'INDUSINDBK.NS',
 'INFY.NS',
 'ITC.NS',
 'JSWSTEEL.NS',
 'KOTAKBANK.NS',
 'LT.NS',
 'M&M.NS',
 'MARUTI.NS',
 'NESTLEIND.NS',
 'NTPC.NS',
 'ONGC.NS',
 'POWERGRID.NS',
 'RELIANCE.NS',
 'SBIN.NS',
 'SBILIFE.NS',
 'SHREECEM.NS',
 'SUNPHARMA.NS',
 'TATAMOTORS.NS',
 'TATASTEEL.NS',
 'TCS.NS',
 'TATACONSUM.NS',
 'TECHM.NS',
 'TITAN.NS',
 'ULTRACEMCO.NS',
 'UPL.NS',
 'WIPRO.NS']

In [39]:
df = yf.download(symbols[36], start='2010-01-01')

[*********************100%***********************]  1 of 1 completed


In [40]:
df

Open         High          Low        Close    Adj Close  \
Date                                                                          
2010-01-04   540.427307   540.427307   506.127411   532.700500   484.266113   
2010-01-05   569.551208   569.551208   527.697937   530.323059   482.104797   
2010-01-06   534.879883   542.111328   530.298279   538.891846   489.894440   
2010-01-07   538.891846   552.265076   533.938782   547.832092   498.021820   
2010-01-08   548.797974   551.670715   542.854309   546.395691   496.716064   
...                 ...          ...          ...          ...          ...   
2022-06-02  2634.000000  2732.449951  2634.000000  2724.300049  2724.300049   
2022-06-03  2744.000000  2817.350098  2742.000000  2779.500000  2779.500000   
2022-06-06  2780.000000  2814.000000  2751.800049  2767.550049  2767.550049   
2022-06-07  2769.899902  2791.100098  2752.050049  2772.750000  2772.750000   
2022-06-08  2772.750000  2781.000000  2716.300049  2724.050049  2724.050049   

              Volume  
Date                  
2010-01-04  35372156  
2010-01-05   9872785  
2010-01-06  10933743  
2010-01-07  12090336  
2010-01-08   6973331  
...              ...  
2022-06-02  10211408  
2022-06-03  11048210  
2022-06-06   5119488  
2022-06-07   5703333  
2022-06-08   5758596  

[3068 rows x 6 columns]

In [41]:
def tacalc(df):
    df['sma200'] = ta.trend.sma_indicator(df.Close, window=200)
    df['rsi'] = ta.momentum.rsi(df.Close, window=10)
    df['signal'] = np.where((df.Close > df.sma200) & (df.rsi<30), True, False)

In [42]:
def getactuals(df):
    buying_dates = []
    selling_dates = []

    for i in range(len(df)-11):
        if df.signal.iloc[i]:
            buying_dates.append(df.iloc[i+1].name)
            for j in range(1,11):
                if df['rsi'].iloc[i+j] > 40:
                    selling_dates.append(df.iloc[i+j+1].name)
                    break
                elif j==10:
                    selling_dates.append(df.iloc[i+j+1].name)
                    
    frame = pd.DataFrame({'buying_dates':buying_dates, 'selling_dates':selling_dates})
    actuals = frame[frame.buying_dates > frame.selling_dates.shift(1)]
    actuals = frame[:1].append(actuals)
                    
    return actuals

In [43]:
tacalc(df)
actuals = getactuals(df)

In [44]:
profits = \
(df.loc[actuals.selling_dates].Open.values - df.loc[actuals.buying_dates].Open.values)/df.loc[actuals.buying_dates].Open.values

In [45]:
profits

array([ 0.00019084,  0.02843363,  0.02002891,  0.02006336,  0.01016343,
        0.00528297,  0.02122538,  0.02764901,  0.05092458,  0.05312251,
        0.00075709, -0.05508072,  0.05775701,  0.01818182,  0.02709644])

In [46]:
sum(profits)

0.2857962463502204

# Test on all companies

In [1]:
matrixprofits = []

for i in range(len(symbols)):
    df = yf.download(symbols[i], start='2010-01-01')
    tacalc(df)
    actualtrades = getactuals(df)
    profits = \
    (df.loc[actualtrades.selling_dates].Open.values - df.loc[actualtrades.buying_dates].Open.values)/df.loc[actualtrades.buying_dates].Open.values
    matrixprofits.append(profits)

NameError: name 'symbols' is not defined

In [48]:
matrixprofits

[array([ 0.03544132,  0.03996283,  0.0781934 ,  0.03566082,  0.01648805,
        -0.00735291,  0.08345534, -0.01976285]),
 array([ 0.03322156,  0.06      ,  0.05348846,  0.06704824,  0.03759927,
        -0.08774725,  0.02192496,  0.04601469,  0.0114735 ]),
 array([ 0.01454819, -0.05200383,  0.01970359,  0.01473509,  0.03332173,
         0.01381691,  0.00242827,  0.04250988,  0.02424489,  0.02418705,
         0.00645161,  0.00245399, -0.11745215,  0.0151762 ,  0.01298701,
         0.01175348,  0.03325416,  0.03565167, -0.07086523,  0.04504132,
         0.0373913 ,  0.04302521,  0.0283871 ]),
 array([ 0.02928576,  0.00602141, -0.00036276,  0.02538071, -0.05785058,
         0.024     ,  0.04823927, -0.0399274 ,  0.03295876,  0.03373416,
        -0.01227981, -0.02779794,  0.05199819,  0.03126525]),
 array([ 0.01084746, -0.04417292,  0.01803069, -0.04101492,  0.00068701,
         0.01224078,  0.01452785,  0.01237998,  0.01467505, -0.00455927,
         0.04020062,  0.01172638, -0.13770053,  

In [49]:
s = 0
for element in matrixprofits:
    s += sum(element)

# Check today

In [53]:
def buysell(df):
    df['sma200'] = ta.trend.sma_indicator(df.Close, window=200)
    df['rsi'] = ta.momentum.rsi(df.Close, window=10)
    df['buy'] = np.where((df.Close > df.sma200) & (df.rsi<30), 'Yes', 'No')
    df['sell'] = np.where((df.Close < df.sma200) | (df.rsi>40), 'Yes', 'No')
    
    print(df)

                  Open        High         Low       Close   Adj Close  \
Date                                                                     
2010-01-04  154.125000  156.825012  152.088760  156.105011  137.027161   
2010-01-05  156.667511  159.300003  156.048752  158.568756  139.189835   
2010-01-06  158.850006  159.750000  154.575012  155.362503  136.375397   
2010-01-07  156.375000  156.487503  151.875000  152.606262  133.956009   
2010-01-08  152.775009  153.000000  149.850006  150.311264  131.941498   
...                ...         ...         ...         ...         ...   
2022-06-02  471.799988  476.450012  468.100006  474.149994  474.149994   
2022-06-03  479.649994  488.000000  474.500000  475.500000  475.500000   
2022-06-06  472.000000  475.500000  464.200012  473.200012  473.200012   
2022-06-07  470.000000  470.750000  465.149994  467.649994  467.649994   
2022-06-08  471.049988  472.000000  464.299988  470.399994  470.399994   

              Volume      sma200     